// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Demo.Report.API.Data.Contexts;
using Microservice.Demo.Report.API.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservice.Demo.Report.API.Data.Contexts.Configurations
{
    public partial class OfferCoverConfiguration : IEntityTypeConfiguration<OfferCover>
    {
        public void Configure(EntityTypeBuilder<OfferCover> entity)
        {
            entity.ToTable("OfferCover");

            entity.Property(e => e.Code)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Price).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.Offer)
                .WithMany(p => p.OfferCovers)
                .HasForeignKey(d => d.OfferId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OfferCoverOffer");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OfferCover> entity);
    }
}
