// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Demo.Report.API.Data.Contexts;
using Microservice.Demo.Report.API.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservice.Demo.Report.API.Data.Contexts.Configurations
{
    public partial class OfferConfiguration : IEntityTypeConfiguration<Offer>
    {
        public void Configure(EntityTypeBuilder<Offer> entity)
        {
            entity.ToTable("Offer");

            entity.Property(e => e.AgentLogin)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Number)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.ProductCode)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.TotalPrice).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.OfferStatus)
                .WithMany(p => p.Offers)
                .HasForeignKey(d => d.OfferStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OfferOfferStatus");

            entity.HasOne(d => d.PolicyHolder)
                .WithMany(p => p.Offers)
                .HasForeignKey(d => d.PolicyHolderId)
                .HasConstraintName("FK_OfferPolicyHolder");

            entity.HasOne(d => d.PolicyValidityPeriod)
                .WithMany(p => p.Offers)
                .HasForeignKey(d => d.PolicyValidityPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OfferPolicyValidityPeriod");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Offer> entity);
    }
}
