// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Demo.Report.API.Data.Contexts;
using Microservice.Demo.Report.API.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservice.Demo.Report.API.Data.Contexts.Configurations
{
    public partial class PolicyStatusConfiguration : IEntityTypeConfiguration<PolicyStatus>
    {
        public void Configure(EntityTypeBuilder<PolicyStatus> entity)
        {
            entity.ToTable("PolicyStatus");

            entity.Property(e => e.Description)
                .HasMaxLength(250)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PolicyStatus> entity);
    }
}
