// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Demo.Report.API.Data.Contexts;
using Microservice.Demo.Report.API.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservice.Demo.Report.API.Data.Contexts.Configurations
{
    public partial class PolicyConfiguration : IEntityTypeConfiguration<Policy>
    {
        public void Configure(EntityTypeBuilder<Policy> entity)
        {
            entity.ToTable("Policy");

            entity.Property(e => e.AgentLogin)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Number)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.ProductCode)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.HasOne(d => d.PolicyStatus)
                .WithMany(p => p.Policies)
                .HasForeignKey(d => d.PolicyStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PolicyPolicyStatus");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Policy> entity);
    }
}
