// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Demo.Report.API.Data.Contexts;
using Microservice.Demo.Report.API.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservice.Demo.Report.API.Data.Contexts.Configurations
{
    public partial class PolicyValidityPeriodConfiguration : IEntityTypeConfiguration<PolicyValidityPeriod>
    {
        public void Configure(EntityTypeBuilder<PolicyValidityPeriod> entity)
        {
            entity.ToTable("PolicyValidityPeriod");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PolicyValidityPeriod> entity);
    }
}
