// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Demo.Report.API.Data.Contexts;
using Microservice.Demo.Report.API.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservice.Demo.Report.API.Data.Contexts.Configurations
{
    public partial class PolicyCoverConfiguration : IEntityTypeConfiguration<PolicyCover>
    {
        public void Configure(EntityTypeBuilder<PolicyCover> entity)
        {
            entity.ToTable("PolicyCover");

            entity.Property(e => e.Code)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Premium).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.PolicyValidityPeriod)
                .WithMany(p => p.PolicyCovers)
                .HasForeignKey(d => d.PolicyValidityPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PolicyCoverPolicyValidityPeriod");

            entity.HasOne(d => d.PolicyVersion)
                .WithMany(p => p.PolicyCovers)
                .HasForeignKey(d => d.PolicyVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PolicyCoverPolicyVersion");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PolicyCover> entity);
    }
}
