// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microservices.Demo.Report.API.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Microservices.Demo.Report.API.Data.Entities.Configurations
{
    public partial class PolicyValidityPeriodConfiguration : IEntityTypeConfiguration<PolicyValidityPeriod>
    {
        public void Configure(EntityTypeBuilder<PolicyValidityPeriod> entity)
        {
            entity.ToTable("PolicyValidityPeriod");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PolicyValidityPeriod> entity);
    }
}
