// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microservices.Demo.Report.API.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Microservices.Demo.Report.API.Data.Entities.Configurations
{
    public partial class PolicyVersionConfiguration : IEntityTypeConfiguration<PolicyVersion>
    {
        public void Configure(EntityTypeBuilder<PolicyVersion> entity)
        {
            entity.ToTable("PolicyVersion");

            entity.Property(e => e.TotalPremiumAmount).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.CoverPeriodPolicyValidityPeriod)
                .WithMany(p => p.PolicyVersionCoverPeriodPolicyValidityPeriods)
                .HasForeignKey(d => d.CoverPeriodPolicyValidityPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PolicyVersionCoverPeriodPolicyValidityPeriod");

            entity.HasOne(d => d.PolicyHolder)
                .WithMany(p => p.PolicyVersions)
                .HasForeignKey(d => d.PolicyHolderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PolicyVersionPolicyHolder");

            entity.HasOne(d => d.Policy)
                .WithMany(p => p.PolicyVersions)
                .HasForeignKey(d => d.PolicyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PolicyVersionPolicy");

            entity.HasOne(d => d.VersionValidityPeriodPolicyValidityPeriod)
                .WithMany(p => p.PolicyVersionVersionValidityPeriodPolicyValidityPeriods)
                .HasForeignKey(d => d.VersionValidityPeriodPolicyValidityPeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PolicyVersionVersionValidityPeriodPolicyValidityPeriod");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PolicyVersion> entity);
    }
}
