// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microservices.Demo.Report.API.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Microservices.Demo.Report.API.Data.Entities.Configurations
{
    public partial class PolicyConfiguration : IEntityTypeConfiguration<Policy>
    {
        public void Configure(EntityTypeBuilder<Policy> entity)
        {
            entity.ToTable("Policy");

            entity.Property(e => e.AgentLogin)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Number)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.ProductCode)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.HasOne(d => d.PolicyStatus)
                .WithMany(p => p.Policies)
                .HasForeignKey(d => d.PolicyStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PolicyPolicyStatus");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Policy> entity);
    }
}
