// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Microservice.Demo.Report.API.Data.Entities
{
    public partial class Message
    {
        public int MessageId { get; set; }
        public string Type { get; set; }
        public string JsonPayload { get; set; }
    }
}